Simple object detection, avoids walls
runestone2023/Group-C pull request #29
Opened 2023-04-19 09:38 UTC by leonpx

Closes #20.

2023-04-19 09:49 UTC, Kax-y requested changes

2023-04-19 09:49 UTC, Kax-y commented on robot/main.py
> +    while obstacle_sensor.distance() > 300:
Move this while loop into a new function "check_for_wall" or "obstacle_ahead" or something like that.

2023-04-19 09:49 UTC, Kax-y commented on robot/main.py
> +while True:
Put this whole while loop into a test function and then run it in "if __name__ == 'main':"

2023-05-02 07:45 UTC, Kax-y submitted a review, later dismissed
Looks good just one minor detail that you could optionally fix

2023-05-02 07:45 UTC, Kax-y commented on robot/control.py
> +def check_for_obstacle(obstacle_sensor):
Shouldn't this function return something? For example True when it detects something and False otherwise?

2023-05-02 09:32 UTC, 00oskpet approved these changes, later dismissed

2023-05-02 09:39 UTC, merged