Feauture/db
runestone2023/Group-C pull request #41
Opened 2023-05-02 07:59 UTC by leonorastiernborg

Database connection and get request from db

2023-05-02 09:53 UTC, Kax-y requested changes
It looks good but just needs some minor changes!
(mostly moving models into the db folder)

2023-05-02 09:53 UTC, Kax-y commented on robosistance/Cargo.toml
> +[dependencies.mongodb]
You can write this on one line if you wish

2023-05-02 09:53 UTC, Kax-y commented on robosistance/src/models/robot_model.rs
> +use mongodb::bson::oid::ObjectId;
I think this file would fit fine in the db folder, I don't think you need another one.

2023-05-02 09:53 UTC, Kax-y commented on robosistance/src/endpoints/db.rs
> +    println!("COMES HERE");
Remove this print. You could add an appropriate log if you wish but I don't think it's needed. This seems to be for testing only.

2023-05-05 07:38 UTC, Kax-y approved these changes
Looks good!

2023-05-05 10:53 UTC, 00oskpet approved these changes

2023-05-05 11:00 UTC, merged