Add the patrol button
runestone2023/Group-C pull request #43
Opened 2023-05-02 14:52 UTC by tienchuotbk

Add new button and a event click that send the patrol request to Backend. 
This button is placed in the robot detail page.

2023-05-02 15:01 UTC, maiduc22 submitted a review, later dismissed
Everything is ok

2023-05-02 15:10 UTC, Kax-y requested changes
Looks good except for that it should be a get request!

2023-05-02 15:10 UTC, Kax-y commented on frontend/src/pages/RobotDetails/RobotDetails.tsx
> +      method: "POST",
```suggestion
      method: "GET",
```

2023-05-03 07:41 UTC, Kax-y approved these changes

2023-05-03 07:41 UTC, merged